check .gitignore

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -33,8 +33,8 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v6.0.2
 
-      - name: List Files 1
-        run: ls -al
+      - name: Check .dockerignore exists
+        run: ls -la .dockerignore || echo "ERROR-> .dockerignore not found!"
 
       - name: Build Docker Image whit debug output
         run: docker build --progress=plain -t attack_on_titan:latest .
